# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170411_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_name',
            new_name='name',
        ),
    ]
