# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170411_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donation_date',
            new_name='donation_date_start',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('e', 'Exact Value: $100'), ('r', 'Range: $100-$200'), ('p', 'Range: $100 and above'), ('o', 'Just other'), ('u', 'Unknown')], default='e', help_text='Donation Type', max_length=1),
        ),
    ]
