# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 04:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170419_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_date_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
