# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170417_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
