# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 04:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170419_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date_entered',
            field=models.DateField(default=datetime.date.today, help_text=b'Date entered into this databse'),
        ),
    ]
