# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_donation_donation_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_class',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donorgroup',
            name='year',
            field=models.FloatField(default='2013', help_text='Year of this group', max_length=200),
        ),
    ]
