# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170417_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorgroup',
            name='year',
            field=models.IntegerField(default='2013', help_text='Year of this group', max_length=200),
        ),
    ]
