# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170407_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(default='NYC', max_length=100),
        ),
    ]
