# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 04:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_donation_date_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date_entered',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text=b'Date entered into this databse'),
        ),
    ]
