# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170417_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorgroup',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Institution'),
        ),
    ]
