# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 04:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20170419_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime.now, help_text=b'Date entered into this database'),
        ),
        migrations.AlterField(
            model_name='donorgroup',
            name='year',
            field=models.IntegerField(blank=True, help_text=b'Year of this group', null=True),
        ),
    ]
