# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20170407_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount_exact',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
        migrations.AddField(
            model_name='donation',
            name='amount_range_high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
        migrations.AddField(
            model_name='donation',
            name='amount_range_low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_full_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(blank=True, choices=[('e', 'Exact Value ie: $100'), ('r', 'Range ie $100-$200'), ('p', 'Range ie $100 and above')], default='d', help_text='Book availability', max_length=1),
        ),
        migrations.AddField(
            model_name='donation',
            name='event_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
