# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20170410_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(blank=True, choices=[('e', 'Exact Value ie: $100'), ('r', 'Range ie $100-$200'), ('p', 'Range ie $100 and above')], default='e', help_text='Donation Type', max_length=1),
        ),
    ]
