# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20170425_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(blank=True, choices=[(b'e', b'Exact Value: $100'), (b'r', b'Range: $100-$200'), (b'p', b'Range: $100 and above'), (b'o', b'Just other'), (b'u', b'Unknown')], default=b'u', help_text=b'Donation Type', max_length=1, null=True),
        ),
    ]
