# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170410_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='amount',
            new_name='amount_other',
        ),
    ]
