# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_institution_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='desc',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.URLField(default=b'http://fpoimg.com/100x100', null=True),
        ),
    ]
