# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20170410_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount_exact',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount_range_high',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount_range_low',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
    ]
