# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20170410_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount_exact',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount_other',
            field=models.CharField(blank=True, help_text='ie: Plus a special gift from our family', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount_range_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount_range_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='data_source_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='data_source_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='event_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
