# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20170410_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount_exact',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For exact values ie: $100', max_digits=99, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount_range_high',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For high end $100-$200', max_digits=99, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount_range_low',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For range low end ie: $100-$200 or for low end of range ie: $100 and above', max_digits=99, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('e', 'Exact Value: $100'), ('r', 'Range: $100-$200'), ('p', 'Range: $100 and above'), ('o', 'Just other')], default='e', help_text='Donation Type', max_length=1),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donorgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Donorgroup'),
        ),
        migrations.RemoveField(
            model_name='donation',
            name='person',
        ),
        migrations.AddField(
            model_name='donation',
            name='person',
            field=models.ManyToManyField(null=True, to='catalog.Person'),
        ),
    ]
