# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20170411_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='person',
        ),
        migrations.AddField(
            model_name='donation',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Person'),
        ),
    ]
